[package]
org = "awike"
name = "payment_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerinax/mysql" = "1.16.1"
"ballerinax/kafka" = "4.9.0"

#[dependencies]
#"ballerina/mysql" = "1.2.2"

#[[dependency]]
#org = "ballerina"
#name = "sql"
#version = "1.2.2"

[[platform.java17.dependency]]
path = "libs/mysql-connector-j-9.4.0.jar"
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "9.4.0"
